// Categories and words for the Impostor game.
// Hints are intentionally vague: never shares a root with the word, never names its main function.
// Colors, vibes, environments, textures. Multiple words in the same category can plausibly share the same hint.

const CATEGORIES = [
  {
    id: "animals",
    name: "Animals",
    emoji: "🐾",
    genericHints: ["Alive", "Wild", "Nature"],
    words: [
      { word: "Elephant", hint: "Grey" },
      { word: "Lion", hint: "Golden" },
      { word: "Tiger", hint: "Orange" },
      { word: "Giraffe", hint: "Yellow" },
      { word: "Zebra", hint: "Contrast" },
      { word: "Monkey", hint: "Silly" },
      { word: "Kangaroo", hint: "Bounce" },
      { word: "Panda", hint: "Sleepy" },
      { word: "Bear", hint: "Warm" },
      { word: "Wolf", hint: "Alone" },
      { word: "Fox", hint: "Sneaky" },
      { word: "Rabbit", hint: "Soft" },
      { word: "Squirrel", hint: "Quick" },
      { word: "Deer", hint: "Gentle" },
      { word: "Horse", hint: "Noble" },
      { word: "Cow", hint: "Slow" },
      { word: "Pig", hint: "Pink" },
      { word: "Sheep", hint: "Cloud" },
      { word: "Goat", hint: "Rough" },
      { word: "Chicken", hint: "Nervous" },
      { word: "Duck", hint: "Yellow" },
      { word: "Eagle", hint: "Free" },
      { word: "Owl", hint: "Wise" },
      { word: "Parrot", hint: "Loud" },
      { word: "Penguin", hint: "Formal" },
      { word: "Ostrich", hint: "Awkward" },
      { word: "Flamingo", hint: "Elegant" },
      { word: "Peacock", hint: "Vain" },
      { word: "Shark", hint: "Fear" },
      { word: "Whale", hint: "Blue" },
      { word: "Dolphin", hint: "Playful" },
      { word: "Octopus", hint: "Alien" },
      { word: "Crab", hint: "Sideways" },
      { word: "Lobster", hint: "Fancy" },
      { word: "Turtle", hint: "Ancient" },
      { word: "Crocodile", hint: "Ancient" },
      { word: "Snake", hint: "Cold" },
      { word: "Frog", hint: "Slimy" },
      { word: "Bee", hint: "Yellow" },
      { word: "Ant", hint: "Team" },
      { word: "Butterfly", hint: "Pretty" },
      { word: "Spider", hint: "Scary" },
      { word: "Mosquito", hint: "Annoying" },
      { word: "Dog", hint: "Happy" },
      { word: "Cat", hint: "Quiet" },
      { word: "Camel", hint: "Golden" },
      { word: "Hippopotamus", hint: "Heavy" },
      { word: "Rhinoceros", hint: "Heavy" },
      { word: "Gorilla", hint: "Strong" },
      { word: "Bat", hint: "Dark" }
    ]
  },
  {
    id: "countries",
    name: "Countries",
    emoji: "🌍",
    genericHints: ["Map", "Nation", "Flag"],
    words: [
      { word: "France", hint: "Fashion" },
      { word: "Germany", hint: "Precise" },
      { word: "Italy", hint: "Warm" },
      { word: "Spain", hint: "Warm" },
      { word: "Portugal", hint: "Coast" },
      { word: "Greece", hint: "Ancient" },
      { word: "United Kingdom", hint: "Rain" },
      { word: "Ireland", hint: "Green" },
      { word: "Netherlands", hint: "Flat" },
      { word: "Belgium", hint: "Small" },
      { word: "Sweden", hint: "Cold" },
      { word: "Norway", hint: "Cold" },
      { word: "Finland", hint: "Cold" },
      { word: "Denmark", hint: "Cold" },
      { word: "Russia", hint: "Huge" },
      { word: "Poland", hint: "History" },
      { word: "Turkey", hint: "Between" },
      { word: "Egypt", hint: "Ancient" },
      { word: "Morocco", hint: "Warm" },
      { word: "Tunisia", hint: "Coast" },
      { word: "Algeria", hint: "Vast" },
      { word: "Nigeria", hint: "Big" },
      { word: "South Africa", hint: "Tip" },
      { word: "Kenya", hint: "Safari" },
      { word: "Ethiopia", hint: "Highland" },
      { word: "Saudi Arabia", hint: "Sand" },
      { word: "United Arab Emirates", hint: "Modern" },
      { word: "Qatar", hint: "Small" },
      { word: "Lebanon", hint: "Small" },
      { word: "Syria", hint: "History" },
      { word: "Jordan", hint: "Rocks" },
      { word: "Iraq", hint: "Rivers" },
      { word: "Iran", hint: "Ancient" },
      { word: "Israel", hint: "Small" },
      { word: "Palestine", hint: "Small" },
      { word: "India", hint: "Colorful" },
      { word: "Pakistan", hint: "Big" },
      { word: "China", hint: "Huge" },
      { word: "Japan", hint: "Small" },
      { word: "South Korea", hint: "Modern" },
      { word: "Thailand", hint: "Warm" },
      { word: "Vietnam", hint: "Long" },
      { word: "Indonesia", hint: "Islands" },
      { word: "Philippines", hint: "Islands" },
      { word: "Australia", hint: "Isolated" },
      { word: "New Zealand", hint: "Isolated" },
      { word: "United States", hint: "Big" },
      { word: "Canada", hint: "Cold" },
      { word: "Mexico", hint: "Warm" },
      { word: "Brazil", hint: "Huge" },
      { word: "Argentina", hint: "Tango" },
      { word: "Chile", hint: "Long" },
      { word: "Colombia", hint: "Coffee" },
      { word: "Peru", hint: "Highland" }
    ]
  },
  {
    id: "food",
    name: "Foods",
    emoji: "🍔",
    genericHints: ["Yum", "Plate", "Meal"],
    words: [
      { word: "Pizza", hint: "Warm" },
      { word: "Burger", hint: "Handheld" },
      { word: "Sushi", hint: "Fresh" },
      { word: "Pasta", hint: "Long" },
      { word: "Tacos", hint: "Bold" },
      { word: "Burrito", hint: "Filled" },
      { word: "Ramen", hint: "Warm" },
      { word: "Sandwich", hint: "Layers" },
      { word: "Hotdog", hint: "Street" },
      { word: "Fries", hint: "Salty" },
      { word: "Salad", hint: "Fresh" },
      { word: "Soup", hint: "Warm" },
      { word: "Steak", hint: "Rich" },
      { word: "Chicken Wings", hint: "Party" },
      { word: "Fried Chicken", hint: "Southern" },
      { word: "Shawarma", hint: "Spice" },
      { word: "Falafel", hint: "Green" },
      { word: "Hummus", hint: "Smooth" },
      { word: "Kebab", hint: "Smoky" },
      { word: "Biryani", hint: "Colorful" },
      { word: "Curry", hint: "Bold" },
      { word: "Pad Thai", hint: "Bright" },
      { word: "Dumplings", hint: "Small" },
      { word: "Croissant", hint: "Buttery" },
      { word: "Pancakes", hint: "Stack" },
      { word: "Waffles", hint: "Grid" },
      { word: "Omelette", hint: "Fluffy" },
      { word: "Cereal", hint: "Bowl" },
      { word: "Bread", hint: "Basic" },
      { word: "Cheese", hint: "Aged" },
      { word: "Yogurt", hint: "Smooth" },
      { word: "Ice Cream", hint: "Cold" },
      { word: "Chocolate", hint: "Rich" },
      { word: "Cake", hint: "Party" },
      { word: "Cookies", hint: "Kids" },
      { word: "Donuts", hint: "Ring" },
      { word: "Cupcake", hint: "Small" },
      { word: "Cheesecake", hint: "Creamy" },
      { word: "Brownie", hint: "Square" },
      { word: "Popcorn", hint: "Cinema" },
      { word: "Chips", hint: "Bag" },
      { word: "Nachos", hint: "Sharing" }
    ]
  },
  {
    id: "sports",
    name: "Sports",
    emoji: "⚽",
    genericHints: ["Move", "Play", "Compete"],
    words: [
      { word: "Football", hint: "Crowd" },
      { word: "Basketball", hint: "Tall" },
      { word: "Tennis", hint: "Quiet" },
      { word: "Badminton", hint: "Light" },
      { word: "Volleyball", hint: "Summer" },
      { word: "Baseball", hint: "Summer" },
      { word: "Cricket", hint: "Long" },
      { word: "Rugby", hint: "Rough" },
      { word: "Hockey", hint: "Fast" },
      { word: "Golf", hint: "Quiet" },
      { word: "Boxing", hint: "Ring" },
      { word: "Wrestling", hint: "Grip" },
      { word: "Karate", hint: "Belt" },
      { word: "Judo", hint: "Throw" },
      { word: "Taekwondo", hint: "Belt" },
      { word: "Swimming", hint: "Blue" },
      { word: "Diving", hint: "Down" },
      { word: "Surfing", hint: "Balance" },
      { word: "Sailing", hint: "Wind" },
      { word: "Rowing", hint: "Rhythm" },
      { word: "Skiing", hint: "White" },
      { word: "Snowboarding", hint: "White" },
      { word: "Ice Skating", hint: "Slide" },
      { word: "Running", hint: "Solo" },
      { word: "Marathon", hint: "Endurance" },
      { word: "Cycling", hint: "Balance" },
      { word: "Skateboarding", hint: "Street" },
      { word: "Bowling", hint: "Indoor" },
      { word: "Archery", hint: "Steady" },
      { word: "Fencing", hint: "Steel" },
      { word: "Gymnastics", hint: "Flex" },
      { word: "Chess", hint: "Silent" },
      { word: "Horse Racing", hint: "Dust" },
      { word: "Formula 1", hint: "Roar" },
      { word: "MMA", hint: "Cage" },
      { word: "Yoga", hint: "Peaceful" },
      { word: "Climbing", hint: "Grip" }
    ]
  },
  {
    id: "objects",
    name: "Objects",
    emoji: "🪑",
    genericHints: ["Thing", "Item", "Common"],
    words: [
      { word: "Chair", hint: "Wooden" },
      { word: "Table", hint: "Flat" },
      { word: "Bed", hint: "Soft" },
      { word: "Sofa", hint: "Soft" },
      { word: "Lamp", hint: "Glow" },
      { word: "Mirror", hint: "Bright" },
      { word: "Clock", hint: "Round" },
      { word: "Watch", hint: "Small" },
      { word: "Phone", hint: "Pocket" },
      { word: "Laptop", hint: "Modern" },
      { word: "Computer", hint: "Modern" },
      { word: "TV", hint: "Living" },
      { word: "Radio", hint: "Old" },
      { word: "Camera", hint: "Memory" },
      { word: "Book", hint: "Quiet" },
      { word: "Notebook", hint: "Paper" },
      { word: "Pen", hint: "Slim" },
      { word: "Pencil", hint: "Slim" },
      { word: "Eraser", hint: "Small" },
      { word: "Ruler", hint: "Straight" },
      { word: "Scissors", hint: "Metal" },
      { word: "Knife", hint: "Metal" },
      { word: "Fork", hint: "Metal" },
      { word: "Spoon", hint: "Metal" },
      { word: "Plate", hint: "Round" },
      { word: "Cup", hint: "Round" },
      { word: "Bottle", hint: "Tall" },
      { word: "Glass", hint: "Fragile" },
      { word: "Pillow", hint: "Soft" },
      { word: "Blanket", hint: "Cozy" },
      { word: "Towel", hint: "Fabric" },
      { word: "Toothbrush", hint: "Morning" },
      { word: "Comb", hint: "Morning" },
      { word: "Umbrella", hint: "Grey" },
      { word: "Wallet", hint: "Pocket" },
      { word: "Bag", hint: "Fabric" },
      { word: "Backpack", hint: "School" },
      { word: "Key", hint: "Metal" },
      { word: "Broom", hint: "Long" },
      { word: "Vacuum", hint: "Loud" },
      { word: "Fan", hint: "Spin" },
      { word: "Fridge", hint: "White" },
      { word: "Oven", hint: "Big" },
      { word: "Microwave", hint: "Box" },
      { word: "Washing Machine", hint: "Loud" },
      { word: "Hammer", hint: "Heavy" },
      { word: "Screwdriver", hint: "Slim" }
    ]
  },
  {
    id: "jobs",
    name: "Jobs",
    emoji: "💼",
    genericHints: ["Work", "Career", "Skill"],
    words: [
      { word: "Doctor", hint: "White" },
      { word: "Nurse", hint: "White" },
      { word: "Dentist", hint: "White" },
      { word: "Pharmacist", hint: "White" },
      { word: "Surgeon", hint: "Steady" },
      { word: "Veterinarian", hint: "Furry" },
      { word: "Teacher", hint: "Patient" },
      { word: "Professor", hint: "Books" },
      { word: "Engineer", hint: "Solve" },
      { word: "Software Developer", hint: "Screen" },
      { word: "Architect", hint: "Vision" },
      { word: "Designer", hint: "Vision" },
      { word: "Lawyer", hint: "Suit" },
      { word: "Judge", hint: "Serious" },
      { word: "Police Officer", hint: "Uniform" },
      { word: "Firefighter", hint: "Brave" },
      { word: "Soldier", hint: "Uniform" },
      { word: "Chef", hint: "Kitchen" },
      { word: "Baker", hint: "Early" },
      { word: "Waiter", hint: "Polite" },
      { word: "Barista", hint: "Morning" },
      { word: "Pilot", hint: "Uniform" },
      { word: "Astronaut", hint: "Rare" },
      { word: "Sailor", hint: "Blue" },
      { word: "Farmer", hint: "Early" },
      { word: "Fisherman", hint: "Patient" },
      { word: "Mechanic", hint: "Dirty" },
      { word: "Electrician", hint: "Careful" },
      { word: "Plumber", hint: "Wet" },
      { word: "Carpenter", hint: "Rough" },
      { word: "Painter", hint: "Messy" },
      { word: "Musician", hint: "Creative" },
      { word: "Singer", hint: "Loud" },
      { word: "Actor", hint: "Fame" },
      { word: "Dancer", hint: "Graceful" },
      { word: "Photographer", hint: "Moment" },
      { word: "Journalist", hint: "Truth" },
      { word: "Writer", hint: "Alone" },
      { word: "Scientist", hint: "Curious" },
      { word: "Accountant", hint: "Precise" },
      { word: "Banker", hint: "Suit" },
      { word: "Athlete", hint: "Fit" },
      { word: "Coach", hint: "Loud" },
      { word: "Referee", hint: "Fair" }
    ]
  },
  {
    id: "fruits",
    name: "Fruits",
    emoji: "🍎",
    genericHints: ["Fresh", "Grow", "Nature"],
    words: [
      { word: "Apple", hint: "Crunch" },
      { word: "Banana", hint: "Curved" },
      { word: "Orange", hint: "Bright" },
      { word: "Lemon", hint: "Sharp" },
      { word: "Lime", hint: "Sharp" },
      { word: "Grape", hint: "Bunch" },
      { word: "Strawberry", hint: "Summer" },
      { word: "Blueberry", hint: "Tiny" },
      { word: "Raspberry", hint: "Tiny" },
      { word: "Watermelon", hint: "Summer" },
      { word: "Cantaloupe", hint: "Summer" },
      { word: "Pineapple", hint: "Tropical" },
      { word: "Mango", hint: "Tropical" },
      { word: "Peach", hint: "Soft" },
      { word: "Pear", hint: "Soft" },
      { word: "Cherry", hint: "Bright" },
      { word: "Plum", hint: "Purple" },
      { word: "Apricot", hint: "Soft" },
      { word: "Kiwi", hint: "Tiny" },
      { word: "Papaya", hint: "Tropical" },
      { word: "Coconut", hint: "Beach" },
      { word: "Avocado", hint: "Creamy" },
      { word: "Pomegranate", hint: "Bright" },
      { word: "Fig", hint: "Ancient" },
      { word: "Date", hint: "Desert" },
      { word: "Guava", hint: "Tropical" },
      { word: "Passion Fruit", hint: "Tropical" },
      { word: "Dragon Fruit", hint: "Wild" },
      { word: "Grapefruit", hint: "Bitter" }
    ]
  },
  {
    id: "vegetables",
    name: "Vegetables",
    emoji: "🥕",
    genericHints: ["Fresh", "Garden", "Healthy"],
    words: [
      { word: "Carrot", hint: "Bright" },
      { word: "Potato", hint: "Basic" },
      { word: "Tomato", hint: "Round" },
      { word: "Cucumber", hint: "Fresh" },
      { word: "Lettuce", hint: "Leafy" },
      { word: "Onion", hint: "Layers" },
      { word: "Garlic", hint: "Strong" },
      { word: "Pepper", hint: "Bold" },
      { word: "Broccoli", hint: "Tree" },
      { word: "Cauliflower", hint: "Cloud" },
      { word: "Cabbage", hint: "Layers" },
      { word: "Spinach", hint: "Leafy" },
      { word: "Kale", hint: "Leafy" },
      { word: "Corn", hint: "Yellow" },
      { word: "Peas", hint: "Tiny" },
      { word: "Beans", hint: "Tiny" },
      { word: "Zucchini", hint: "Long" },
      { word: "Eggplant", hint: "Shiny" },
      { word: "Pumpkin", hint: "Autumn" },
      { word: "Radish", hint: "Bright" },
      { word: "Beet", hint: "Bright" },
      { word: "Celery", hint: "Long" },
      { word: "Asparagus", hint: "Long" },
      { word: "Mushroom", hint: "Damp" },
      { word: "Okra", hint: "Slim" },
      { word: "Sweet Potato", hint: "Warm" },
      { word: "Ginger", hint: "Sharp" }
    ]
  },
  {
    id: "vehicles",
    name: "Vehicles",
    emoji: "🚗",
    genericHints: ["Move", "Wheels", "Travel"],
    words: [
      { word: "Car", hint: "Common" },
      { word: "Truck", hint: "Heavy" },
      { word: "Bus", hint: "Crowd" },
      { word: "Motorcycle", hint: "Loud" },
      { word: "Bicycle", hint: "Silent" },
      { word: "Scooter", hint: "Small" },
      { word: "Skateboard", hint: "Street" },
      { word: "Train", hint: "Long" },
      { word: "Tram", hint: "City" },
      { word: "Subway", hint: "City" },
      { word: "Airplane", hint: "High" },
      { word: "Helicopter", hint: "Loud" },
      { word: "Rocket", hint: "Fire" },
      { word: "Ship", hint: "Blue" },
      { word: "Boat", hint: "Blue" },
      { word: "Yacht", hint: "Luxury" },
      { word: "Submarine", hint: "Silent" },
      { word: "Kayak", hint: "Slim" },
      { word: "Canoe", hint: "Slim" },
      { word: "Ambulance", hint: "Loud" },
      { word: "Fire Truck", hint: "Loud" },
      { word: "Police Car", hint: "Loud" },
      { word: "Taxi", hint: "City" },
      { word: "Limousine", hint: "Luxury" },
      { word: "Tractor", hint: "Field" },
      { word: "Bulldozer", hint: "Heavy" },
      { word: "Crane", hint: "Tall" },
      { word: "Hot Air Balloon", hint: "Float" }
    ]
  },
  {
    id: "nature",
    name: "Nature",
    emoji: "🌳",
    genericHints: ["Outside", "Earth", "Natural"],
    words: [
      { word: "Tree", hint: "Old" },
      { word: "Flower", hint: "Bright" },
      { word: "Grass", hint: "Soft" },
      { word: "Bush", hint: "Small" },
      { word: "Cactus", hint: "Warm" },
      { word: "Rose", hint: "Romantic" },
      { word: "Tulip", hint: "Spring" },
      { word: "Sunflower", hint: "Bright" },
      { word: "Mountain", hint: "Silent" },
      { word: "Hill", hint: "Small" },
      { word: "Valley", hint: "Silent" },
      { word: "River", hint: "Blue" },
      { word: "Lake", hint: "Blue" },
      { word: "Ocean", hint: "Blue" },
      { word: "Sea", hint: "Blue" },
      { word: "Waterfall", hint: "Loud" },
      { word: "Beach", hint: "Warm" },
      { word: "Desert", hint: "Empty" },
      { word: "Forest", hint: "Dark" },
      { word: "Jungle", hint: "Dense" },
      { word: "Volcano", hint: "Danger" },
      { word: "Cave", hint: "Silent" },
      { word: "Island", hint: "Alone" },
      { word: "Sun", hint: "Bright" },
      { word: "Moon", hint: "Silver" },
      { word: "Star", hint: "Tiny" },
      { word: "Cloud", hint: "Soft" },
      { word: "Rain", hint: "Grey" },
      { word: "Snow", hint: "White" },
      { word: "Lightning", hint: "Danger" },
      { word: "Rainbow", hint: "Rare" },
      { word: "Wind", hint: "Invisible" },
      { word: "Fog", hint: "Grey" },
      { word: "Storm", hint: "Grey" },
      { word: "Earthquake", hint: "Danger" }
    ]
  },
  {
    id: "tech",
    name: "Technology",
    emoji: "📱",
    genericHints: ["Modern", "Digital", "Gadget"],
    words: [
      { word: "Smartphone", hint: "Pocket" },
      { word: "Tablet", hint: "Flat" },
      { word: "Laptop", hint: "Portable" },
      { word: "Desktop Computer", hint: "Home" },
      { word: "Monitor", hint: "Flat" },
      { word: "Keyboard", hint: "Fingers" },
      { word: "Mouse", hint: "Small" },
      { word: "Printer", hint: "Loud" },
      { word: "Scanner", hint: "Office" },
      { word: "Router", hint: "Blinking" },
      { word: "Modem", hint: "Blinking" },
      { word: "WiFi", hint: "Invisible" },
      { word: "Bluetooth", hint: "Invisible" },
      { word: "USB", hint: "Small" },
      { word: "Charger", hint: "Wire" },
      { word: "Headphones", hint: "Music" },
      { word: "Earbuds", hint: "Tiny" },
      { word: "Speaker", hint: "Loud" },
      { word: "Camera", hint: "Moment" },
      { word: "Drone", hint: "Buzz" },
      { word: "Smartwatch", hint: "Wrist" },
      { word: "VR Headset", hint: "Immersive" },
      { word: "Console", hint: "Home" },
      { word: "Controller", hint: "Hands" },
      { word: "Robot", hint: "Future" },
      { word: "Artificial Intelligence", hint: "Future" },
      { word: "Cloud Storage", hint: "Invisible" },
      { word: "Email", hint: "Daily" },
      { word: "Social Media", hint: "Daily" },
      { word: "Website", hint: "Daily" },
      { word: "App", hint: "Tap" },
      { word: "Video Game", hint: "Fun" }
    ]
  },
  {
    id: "clothing",
    name: "Clothing",
    emoji: "👕",
    genericHints: ["Wear", "Fabric", "Style"],
    words: [
      { word: "T-Shirt", hint: "Casual" },
      { word: "Shirt", hint: "Common" },
      { word: "Hoodie", hint: "Cozy" },
      { word: "Sweater", hint: "Cozy" },
      { word: "Jacket", hint: "Autumn" },
      { word: "Coat", hint: "Winter" },
      { word: "Blazer", hint: "Formal" },
      { word: "Suit", hint: "Formal" },
      { word: "Dress", hint: "Elegant" },
      { word: "Skirt", hint: "Elegant" },
      { word: "Jeans", hint: "Blue" },
      { word: "Pants", hint: "Common" },
      { word: "Shorts", hint: "Summer" },
      { word: "Underwear", hint: "Hidden" },
      { word: "Socks", hint: "Pair" },
      { word: "Shoes", hint: "Pair" },
      { word: "Sneakers", hint: "Casual" },
      { word: "Sandals", hint: "Summer" },
      { word: "Boots", hint: "Heavy" },
      { word: "Hat", hint: "Round" },
      { word: "Cap", hint: "Round" },
      { word: "Scarf", hint: "Long" },
      { word: "Gloves", hint: "Pair" },
      { word: "Belt", hint: "Long" },
      { word: "Tie", hint: "Formal" },
      { word: "Bow Tie", hint: "Formal" },
      { word: "Sunglasses", hint: "Cool" },
      { word: "Pajamas", hint: "Night" },
      { word: "Swimsuit", hint: "Summer" },
      { word: "Raincoat", hint: "Grey" }
    ]
  },
  {
    id: "instruments",
    name: "Instruments",
    emoji: "🎸",
    genericHints: ["Sound", "Melody", "Play"],
    words: [
      { word: "Guitar", hint: "Cool" },
      { word: "Piano", hint: "Elegant" },
      { word: "Violin", hint: "Elegant" },
      { word: "Cello", hint: "Deep" },
      { word: "Drums", hint: "Loud" },
      { word: "Flute", hint: "Light" },
      { word: "Saxophone", hint: "Smooth" },
      { word: "Trumpet", hint: "Bright" },
      { word: "Trombone", hint: "Bold" },
      { word: "Clarinet", hint: "Light" },
      { word: "Harp", hint: "Elegant" },
      { word: "Accordion", hint: "Folk" },
      { word: "Harmonica", hint: "Pocket" },
      { word: "Xylophone", hint: "Bright" },
      { word: "Tambourine", hint: "Rhythm" },
      { word: "Banjo", hint: "Folk" },
      { word: "Ukulele", hint: "Tropical" },
      { word: "Bass", hint: "Deep" },
      { word: "Bagpipes", hint: "Traditional" },
      { word: "Oboe", hint: "Sharp" },
      { word: "Keyboard", hint: "Modern" },
      { word: "Organ", hint: "Old" },
      { word: "Maracas", hint: "Rhythm" }
    ]
  },
  {
    id: "places",
    name: "Places",
    emoji: "🏛️",
    genericHints: ["Go", "Visit", "Spot"],
    words: [
      { word: "School", hint: "Busy" },
      { word: "University", hint: "Big" },
      { word: "Hospital", hint: "White" },
      { word: "Airport", hint: "Busy" },
      { word: "Train Station", hint: "Busy" },
      { word: "Bus Stop", hint: "Small" },
      { word: "Restaurant", hint: "Warm" },
      { word: "Cafe", hint: "Small" },
      { word: "Bar", hint: "Night" },
      { word: "Hotel", hint: "Modern" },
      { word: "Beach", hint: "Warm" },
      { word: "Park", hint: "Open" },
      { word: "Zoo", hint: "Wild" },
      { word: "Museum", hint: "Quiet" },
      { word: "Library", hint: "Quiet" },
      { word: "Cinema", hint: "Dark" },
      { word: "Theater", hint: "Show" },
      { word: "Stadium", hint: "Huge" },
      { word: "Gym", hint: "Sweat" },
      { word: "Mall", hint: "Bright" },
      { word: "Market", hint: "Colorful" },
      { word: "Supermarket", hint: "Bright" },
      { word: "Pharmacy", hint: "Small" },
      { word: "Bank", hint: "Serious" },
      { word: "Post Office", hint: "Old" },
      { word: "Church", hint: "Silent" },
      { word: "Mosque", hint: "Silent" },
      { word: "Temple", hint: "Silent" },
      { word: "Castle", hint: "Old" },
      { word: "Palace", hint: "Luxury" },
      { word: "Farm", hint: "Green" },
      { word: "Prison", hint: "Grey" },
      { word: "Police Station", hint: "Serious" },
      { word: "Fire Station", hint: "Ready" },
      { word: "Beach Resort", hint: "Sunny" },
      { word: "Amusement Park", hint: "Loud" }
    ]
  },
  {
    id: "colors",
    name: "Colors",
    emoji: "🎨",
    genericHints: ["Bright", "Shade", "Hue"],
    words: [
      { word: "Red", hint: "Warm" },
      { word: "Blue", hint: "Cool" },
      { word: "Green", hint: "Nature" },
      { word: "Yellow", hint: "Bright" },
      { word: "Orange", hint: "Warm" },
      { word: "Purple", hint: "Royal" },
      { word: "Pink", hint: "Soft" },
      { word: "Brown", hint: "Earth" },
      { word: "Black", hint: "Deep" },
      { word: "White", hint: "Pure" },
      { word: "Gray", hint: "Neutral" },
      { word: "Cyan", hint: "Bright" },
      { word: "Magenta", hint: "Bold" },
      { word: "Turquoise", hint: "Cool" },
      { word: "Gold", hint: "Rich" },
      { word: "Silver", hint: "Cool" },
      { word: "Beige", hint: "Neutral" },
      { word: "Navy", hint: "Deep" },
      { word: "Maroon", hint: "Deep" },
      { word: "Lime", hint: "Bright" },
      { word: "Coral", hint: "Warm" },
      { word: "Lavender", hint: "Soft" },
      { word: "Indigo", hint: "Deep" }
    ]
  },
  {
    id: "drinks",
    name: "Drinks",
    emoji: "🥤",
    genericHints: ["Sip", "Cup", "Liquid"],
    words: [
      { word: "Water", hint: "Basic" },
      { word: "Coffee", hint: "Morning" },
      { word: "Tea", hint: "Calm" },
      { word: "Milk", hint: "Kids" },
      { word: "Orange Juice", hint: "Morning" },
      { word: "Apple Juice", hint: "Kids" },
      { word: "Lemonade", hint: "Summer" },
      { word: "Coca Cola", hint: "Brand" },
      { word: "Pepsi", hint: "Brand" },
      { word: "Sprite", hint: "Green" },
      { word: "Fanta", hint: "Bright" },
      { word: "Beer", hint: "Golden" },
      { word: "Wine", hint: "Dinner" },
      { word: "Champagne", hint: "Celebrate" },
      { word: "Whiskey", hint: "Strong" },
      { word: "Vodka", hint: "Clear" },
      { word: "Cocktail", hint: "Colorful" },
      { word: "Smoothie", hint: "Healthy" },
      { word: "Milkshake", hint: "Kids" },
      { word: "Hot Chocolate", hint: "Winter" },
      { word: "Iced Tea", hint: "Summer" },
      { word: "Iced Coffee", hint: "Summer" },
      { word: "Energy Drink", hint: "Late" },
      { word: "Sports Drink", hint: "Bright" },
      { word: "Sparkling Water", hint: "Clear" }
    ]
  }
];
